version: '2'
services:
  gitlab-webhooks:
    image: sunhaojava/blog-webhooks:latest
    container_name: blog-webhooks
    restart: always
    network_mode: "bridge"
    ports:
      - "9098:3000"
    environment:
      # 钉钉机器人的token
      - DING_TOKEN=${DING_TOKEN}
      # 博客列表
      - blog_nginx_dest=/home/nginx/www/blog
    env_file:
      - .env