version: '2'
services:
  gitlab-webhooks:
    image: sunhaojava/blog-webhooks:latest
    container_name: blog-webhooks
    restart: always
    network_mode: "bridge"
    ports:
      - "9098:3000"
    environment:
      # 钉钉机器人的token
      - DING_TOKEN=${DING_TOKEN}
      # 博客列表
      - blog_nginx_dest=/home/dist/blog
      - lodsve_documents_nginx_dest=/home/helps
    env_file:
      - .env
    volumes:
      # blog在宿主机上的静态文件路径
      - ${DOCKER_VOLUME}/nginx/data/blog:/home/dist/blog
      # helps在宿主机上的静态文件路径
      - ${DOCKER_VOLUME}/nginx/data/helps:/home/dist/helps
      # 预先在宿主机上git clone好代码
      - ${DOCKER_VOLUME}/blog-webhooks/workspaces:/home/workspaces